
// <auto-generated>
//      This code was generated using T4 text template
//      Generated at 07/07/2017 16:33:09
//
//      Changes to this file may cause incorrect behaviour and will be lost 
//      if the code is regenerated.
// </auto-generated>

namespace Polygon.Diagnostics
{
    /// <summary>
    ///     Уровень логирования
    /// </summary>
    [JetBrains.Annotations.PublicAPI]
    public enum LogLevel
    {
        /// <summary>
        ///     Сообщение трассировки
        /// </summary>
        Trace,
        /// <summary>
        ///     Отладочное сообщение
        /// </summary>
        Debug,
        /// <summary>
        ///     Информационное сообщение
        /// </summary>
        Info,
        /// <summary>
        ///     Предупреждение
        /// </summary>
        Warn,
        /// <summary>
        ///     Некритическая ошибка
        /// </summary>
        Error,
        /// <summary>
        ///     Критическая ошибка
        /// </summary>
        Fatal,
    }
}
